name: my-first-ga

on:
  push:
    branches: "github-actions-test"
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v3
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: 6.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
    - name: Prints
      run: |
        echo "hello world"
        pwd
        ls ~
        echo "Test_var:"
        echo ${{ env.TEST_VAR }}
        echo ${{ env.First.TEST_VAR }}
        echo "Test_var simply:"
        echo $env.TEST_VAR
        echo $env.First.TEST_VAR
        echo ".NET ver:" && dotnet --version        
        echo "goodbye world"
#       ls -R ./bin/Debug/net6.0
#     - name: Add a file
