name: my-first-ga

on:
  push:
    branches: "github-actions-test"
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prints
      run: |
        echo "hello world"
        dotnet --version
        ls
        echo "goodbye world"
