name: my-first-ga

on:
  push:
    branches: "github-actions-test"
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v3
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: 6.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
    - name: Prints
      run: |
        echo "hello world"
        pwd
        ls -l ~        
        echo "Test_secret:"       
        echo ${{ secrets.TEST_SECRET1 }}                    
        echo ${{ vars.TEST_SECRET1 }} > ~/test1.txt
        ls -l ~
        echo "in file:"
        cat ~/test1.txt
        apt list --installed | grep ssh
        sshpass -p ${{ secrets.N_P }} scp ~/test1.txt nonroot@195.43.142.14:~/temp
        echo ".NET ver:" && dotnet --version        
        echo "goodbye world"
#       ls -R ./bin/Debug/net6.0
#     - name: Add a file

#         echo "Test_repo_var:"       
#         echo ${{ vars.TEST_REPO_VAR }}                    
#         echo ${{ vars.TEST_REPO_VAR }} > ~/test1.txt
#         echo "in file:"
#         cat ~/test1.txt
